import esbuild from "esbuild";

const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */\n" +
  "/* If you want to view the source, please visit the github repository of this plugin */";

const prod = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "@codemirror/view", "@codemirror/state", "@codemirror/language"],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  // Inline while developing, so a stack trace in the console points at a
  // TypeScript line. In production the map is written beside the bundle and
  // attached to the release instead: inlining it made main.js six times its
  // size, and Obsidian parses that file on every start, on every phone. A
  // report's stack trace is symbolicated against the release's map by hand.
  sourcemap: prod ? "external" : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  await context.dispose();
}
