import esbuild from "esbuild";

const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */\n" +
  "/* If you want to view the source, please visit the github repository of this plugin */";

const prod = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "@codemirror/view", "@codemirror/state"],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  await context.dispose();
}
