import esbuild from "esbuild";

const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */\n" +
  "/* If you want to view the source, please visit the github repository of this plugin */";

const prod = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

// The model runtime is built on its own, as one self-contained browser bundle,
// so the ML library never enters main.js as code: main.js carries it as a
// string and hands it to a Web Worker, or to an iframe where Workers are
// blocked. The same bundle serves both and tells which it is at runtime, so it
// is inlined once. Only what main.js imports reaches the release — until the
// engine is wired in, the string is tree-shaken away with the code that reads it.
const embeddingBuild = await esbuild.build({
  entryPoints: ["src/controllers/semantic/host/frame/entry.ts"],
  bundle: true,
  platform: "browser",
  format: "esm",
  target: "esnext",
  write: false,
  minify: prod,
  logLevel: "warning"
});
const embeddingSource = embeddingBuild.outputFiles[0].text;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  define: {
    __EMBEDDING_BUNDLE_PLACEHOLDER__: JSON.stringify(embeddingSource)
  },
  external: ["obsidian", "@codemirror/view", "@codemirror/state", "@codemirror/language"],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  // Inline while developing, so a stack trace in the console points at a
  // TypeScript line. In production the map is written beside the bundle and
  // attached to the release instead: inlining it made main.js six times its
  // size, and Obsidian parses that file on every start, on every phone. A
  // report's stack trace is symbolicated against the release's map by hand.
  sourcemap: prod ? "external" : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  await context.dispose();
}
